# Generated by Django 5.2.7 on 2025-10-22 06:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=100, verbose_name='Student Name')),
                ('deposited_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('final_total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('returned_change', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('session_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Customer Session',
                'verbose_name_plural': 'Customer Sessions',
            },
        ),
        migrations.CreateModel(
            name='VendingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('available_quantity', models.PositiveIntegerField(default=30)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('category', models.CharField(choices=[('snacks', 'Cakes & Snacks'), ('drinks', 'Soft Drinks')], default='snacks', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vending Product',
                'verbose_name_plural': 'Vending Products',
                'ordering': ['category', 'product_name'],
            },
        ),
        migrations.CreateModel(
            name='MoneyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.DecimalField(decimal_places=2, max_digits=6)),
                ('count', models.IntegerField()),
                ('type', models.CharField(choices=[('inserted', 'Inserted'), ('change', 'Change Returned')], max_length=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominations', to='machine_app.customersession')),
            ],
            options={
                'verbose_name': 'Money Transaction',
                'verbose_name_plural': 'Money Transactions',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('refill', 'Refill')], default='purchase', max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='machine_app.customersession')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine_app.vendingproduct')),
            ],
        ),
    ]
