# Generated by Django 5.2.7 on 2025-10-22 07:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneytransaction',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
